GET http://localhost:5000/user

###
POST http://localhost:5000/user
Content-Type: application/json


{

    "name" : "Sopia Refaldi",
    "email" : "sopia@gmail.com",
    "password" : "123456",
    "confPassword" : "123456"
}


###
POST http://localhost:5000/login
Content-Type: application/json

{
    "email" : "sopia@gmail.com",
    "password" : "123456"

}


###
GET http://localhost:5000/token
